service: raredex-backend-api
useDotenv: true

# Create an optimized package for our functions
package:
  individually: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-dynamodb-local
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:custom.serviceEnv}
  role: GlobalLambdaRole
  profile: raredex
  memorySize: 256

  logs:
    restApi: true

  tracing:
    apiGateway: true
    lambda: true

  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*

custom:
  serviceEnv: ${self:service}-${self:provider.stage}
  dynamodb:
    start:
      migrate: true
    stages:
      - dev

  # Plugins
  webpack: ${file(serverless/resources/webpack.yml)}

  prune:
    automatic: true
    number: 10

functions:
  - ${file(src/services/web-api/functions.yml)}

resources:
  - ${file(serverless/resources/global-role.yml)}
  - ${file(src/services/web-api/collections.yml)}